export const brands = [
  "All",
  "R13",
  "Loewe",
  "Scarosso",
  "Genny",
  "Valentino Garavani",
  "Dorothee Schumacher",
  "Gucci",
  "Dsquared2",
  "Pinko",
  "Alecander Wang",
  "Versace Jeans",
  "Brunello Cucinelli",
  "Acler",
  "Haikure",
  "Kitsuné",
  "Philipp Plein",
  "Moschino",
  "Etro",
  "Patrizia Pepe",
  "Semicouture",
  "Diesel",
  "RE/DONE",
  "b+ab",
  "Adriano Goldschmied",
  "AGOLDE",
  "Calvin Klein",
  "PURPLE BRAND",
  "Tom Ford",
  "Balenciaga",
  "Samsøe & Samsøe",
  "Gestuz",
  "Vivienne Westwood",
  "Mason Margiela",
  "Brunello Cucinelli",
  "Frame Denim",
  "Mother",
  "J.W.Anderson",
  "John Elliot + Co",
  "DEL CORE",
  "Société Anonyme",
  "L'Agence",
  "Stella McCartney"
];
